version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "9500:9500"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:9500
    restart: unless-stopped